name: Generate UML Diagrams

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install PlantUML
      run: sudo apt-get update && sudo apt-get install -y plantuml

    - name: Generate UML Diagrams
      run: |
        mkdir -p diagrams
        find . -name '*.cpp' -exec sh -c 'plantuml -tpng $1 && mv ${1%.cpp}.png diagrams/' _ {} \;
        ls -la diagrams

    - name: Upload UML Diagrams
      uses: actions/upload-artifact@v2
      with:
        name: UML Diagrams
        path: diagrams
